In [5]:
import os
import pandas as pd
import openpyxl
from datetime import date
import matplotlib.pyplot as plt
import numpy as np
import glob

## MONITORAMENTO MENSAL DO CONSUMO DE ÁGUA DA UFSC 2013 - 2024

##### Outrobro/2024

### Importação e estrutura de organização dos dados MENSAIS 2013/01 a 2024/09
#### - Parte 0 - Funções para obter CSVs a partir de um arquivo excel
#### - Parte 1 - Visualização de dados importados a partir do dicionário gerado, dfs ainda separadas
#### - Parte 2 - Visualização de informações a partir de um único df

##### Nome: Djesser Zechner Sergio

##### https://github.com/Djesser/ENS410064.git

### Parte 0 - Funções para obter CSVs a partir de um arquivo excel

In [10]:

#--------------------------------------------------------------------------------------------------------------------------------
#Main_def-1 - gerar_csv_dados_agua_a_partir_arquivo_xls(nome_arquivo_xls):

def gerar_csvs_a_partir_excel_func(nome_arquivo_xls):
    
    #sub-def1
    pasta_projeto = pasta_projeto_func()
    #sub-def2
    pasta_dados_origem = pasta_dados_origem_func(pasta_projeto)
    #sub-def3
    xls_file = xls_para_csvs_separados(pasta_dados_origem, nome_arquivo_xls)
    #sub-def4
    pasta_dados_csv = pasta_dados_csv_func(pasta_dados_origem)
    #sub-def5
    gerar_csvs(xls_file, pasta_dados_csv)
    
#sub-def 1: -------------------------------------

def pasta_projeto_func():
    # identificando pasta de trabalho
    pasta_projeto = r'I:\Meu Drive\UFSC\PPGEA 2024\Python_for_env\ENS410064\Projeto'
    print('Pasta projeto: ', pasta_projeto)
    return pasta_projeto

#sub-def 2: -------------------------------------

def  pasta_dados_origem_func(pasta_projeto):
    pasta_dados_origem = os.path.join(pasta_projeto, 'Dados','Origem')
    print('\n','Pasta dados origem :', pasta_dados_origem)
    
    #definir pasta:
    os.chdir(pasta_dados_origem)

    return pasta_dados_origem


#sub-def 3: -------------------------------------

def xls_para_csvs_separados(pasta_dados_origem, nome_arquivo_xls):

    # Read Excel file into a Pandas ExcelFile object 
    #https://www.geeksforgeeks.org/exporting-multiple-sheets-as-csv-using-python/

    #xls_caminho = 
    xls_file = pd.ExcelFile(os.path.join(pasta_dados_origem, nome_arquivo_xls))
    display(xls_file)

    return xls_file

#sub-def 4: -------------------------------------

def pasta_dados_csv_func(pasta_dados_origem):
    
    pasta_dados_csv = os.path.join(pasta_dados_origem, "CSVs")
    print('Pasta dados csv:', pasta_dados_csv)
    try:
        os.mkdir(pasta_dados_csv)
    except:
        pass
    return pasta_dados_csv
 
#sub-def 5: -------------------------------------

# Percorrer cada planilha do arquivo excel e exporta para csv
def gerar_csvs(xls_file, pasta_dados_csv):
    os.chdir(pasta_dados_csv)
    total_csvs_exportados = 0
    for sheet_name in xls_file.sheet_names:
        df = pd.read_excel(xls_file, sheet_name)
        #print(sheet_name)
        # Export the DataFrame to a CSV file
        df.to_csv(f'{sheet_name}.csv', index=False)
        total_csvs_exportados +=1
    total_csvs_pasta = 0
    for file in glob.glob('*.csv'):
        total_csvs_pasta +=1
        
    print('\n', f'CSVs exportados com sucesso para a pasta {pasta_dados_csv}.')
    print('\n', f'Foram exportados {total_csvs_exportados} arquivos com extensão csv.')
    print('\n', f'A pasta CSV possui ao todo {total_csvs_pasta} arquivos csv.')


#------------------------------------------------------------------------------------------------------------------------------
#main_def-2 - gerar dicionário a partir de csvs previamente salvos
def gerar_e_corrigir_dicionario_a_partir_csvs_func():
    #sub-def1
    pasta_projeto = pasta_projeto_func()
    #sub-def2
    pasta_dados_origem = pasta_dados_origem_func(pasta_projeto)
    #sub-def4
    pasta_dados_csv = pasta_dados_csv_func(pasta_dados_origem)
    #sub-def6
    dict_dfs = adicionar_csv_dicionario(pasta_dados_csv)
    #sub-def7
    dict_dfs = reordenar_dicionario(dict_dfs)
    #sub-def8
    dict_dfs = retirar_csvs_de_cadastro(dict_dfs)
    #sub-def9
    verificar_n_colunas_dicionario(dict_dfs)

    return dict_dfs


#sub-def 6: -------------------------------------

# Percorrer cada csv, converter em dataframe e adicionar a um dicionário:
def adicionar_csv_dicionario(pasta_dados_csv):
    os.chdir(pasta_dados_csv)
    dict_dfs = {}
    for csv in os.listdir(pasta_dados_csv):
        nome = (f'{csv[:-4]}_df')
        df = pd.read_csv(csv)
        dict_dfs[nome] = df
    
    lista_dict_dfs_chaves = dict_dfs.keys()
    return dict_dfs

#sub-def 7: -------------------------------------

# Percorrer cada csv, converter em dataframe e adicionar a um dicionário:
def reordenar_dicionario(dict_dfs):
    lista_dict_dfs_chaves = list(dict_dfs.keys())
    lista_dict_dfs_chaves.sort()
    sorted_dict_dfs = {}
    # Sorted Dictionary
    for chave in lista_dict_dfs_chaves:
        sorted_dict_dfs[chave] = dict_dfs[chave]
    print(sorted_dict_dfs.keys())
    return sorted_dict_dfs

#sub-def 8: -------------------------------------

def retirar_csvs_de_cadastro(dict_dfs):
    # retirar csvs que não precisam no momento, (slicing dictionary)
    dict_dfs = dict(list(dict_dfs.items())[:-2])

    # acessar as chaves do dicionário e converter em lista
    lista_dict_dfs_chaves = dict_dfs.keys()
    return dict_dfs
    
#sub-def 9: -------------------------------------

#verificar se todos os dataframes do dicionário possuem o mesmo número de colunas
def verificar_n_colunas_dicionario(dict_dfs):
    lista_colunas= []
    verificador=[]
    print('\n','Verificação do número de colunas importadas em cada df:', '\n')
    for i, chave in enumerate(dict_dfs):
        lista_colunas.append(list(dict_dfs[chave].columns))
        if len(lista_colunas) == 1:
            verificador.append(True)
            pass
        else:
            if lista_colunas[i-1] == lista_colunas[i]:
                verificador.append(True)
            else:
                verificador.append(False)
        print(i, chave, len(list(dict_dfs[chave].columns)), verificador[i])
    
    # https://stackoverflow.com/questions/12765833/counting-the-number-of-true-booleans-in-a-python-list
    if sum(verificador) == len(verificador):
        print('\n',f'Todos os {i} dfs importados possuem o mesmo número de colunas, {lista_colunas[i]}')
    else:
        print('\n', "Número de colunas não é o mesmo em todos os df, verificar e corrigir df importados")


#--------------------------------------------------------------------------------------------------------------------------------------
## Main_def 3 - junta dfs em um único df e exporta csv único, dados_agua_df e dados_agua_csv

def juntar_dfs_remover_NAN_e_exportar_func(chave, dict_dfs): 

    pasta_projeto = pasta_projeto_func()
    # sub-def-10:
    dados_agua_df = dataframe_vazio(chave, dict_dfs)
    # sub-def-11:
    dados_agua_df = concat_df_dict(dict_dfs, dados_agua_df)
    # sub-def-12:
    dados_agua_df = verificar_e_remover_NAN_de_dados_agua_df(dados_agua_df)
    # sub-def-13:
    dados_agua_df = corrigir_texto_mes_e_cria_coluna_mesN(dados_agua_df)
    # sub-def-14:
    dados_agua_df = inserir_coluna_datetime(dados_agua_df)
    # sub-def-15:
    dados_agua_df = remover_colunas(dados_agua_df)
    # sub-def-16:
    exportar_pd_unico_to_csv(dados_agua_df, pasta_projeto)
    return dados_agua_df

#sub-def 10: -------------------------------------
### - criando um dataframe vazio com as colunas existentes de um dataframe escolhido:

def dataframe_vazio (chave, dict_dfs):
    columns_lista = list(dict_dfs[chave].columns)
    dados_agua_df = pd.DataFrame (columns = columns_lista)
    return dados_agua_df
    
#sub-def 11: -------------------------------------
## - concatenar todos os dataframes em um único dataframe, 

def concat_df_dict (dict_dfs, dados_agua_df):
    for chave in dict_dfs:
        dados_agua_df = pd.concat([dados_agua_df, dict_dfs[chave]], ignore_index=True)
    print('\n',f'dados_agua_df concatenado em um único arquivo dados_agua_df')
    return dados_agua_df

#sub-def 12: -------------------------------------
## - verificar e contar número de linhas com NAN na coluna ANO

def verificar_e_remover_NAN_de_dados_agua_df(dados_agua_df):
    
    conta_nan = 0
    for i, item in enumerate(dados_agua_df['ANO']):
        if pd.isna(dados_agua_df.iloc[i,2]) == True:
            conta_nan += 1
        else:
            pass
    linhas_dados_agua_df = len(dados_agua_df['ANO'])
    print('\n', f'Total de linhas em dados_agua_df: {linhas_dados_agua_df}. Total de NANs em dados_agua_df: {conta_nan}')
    linhas_resultantes = linhas_dados_agua_df - conta_nan
    
    # comando drop para remover NAN de dados_agua_df
    dados_agua_df = dados_agua_df.dropna(subset=['ANO'])
    
    dados_agua_df = dados_agua_df.reset_index(drop=True) # IMPORTANTE (PRECISA RESETAR O INDEX SENÃO HAVERÁ FALHAS NO DF FINAL]!!!!!!!!!!!!!!!
    
    return dados_agua_df

#sub-def 13: -------------------------------------
## - corrige texto da coluna Mês e associa a coluna mês-N o número do mês

def corrigir_texto_mes_e_cria_coluna_mesN (dados_agua_df):
        
    meses = ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro']
    meses_n = np.arange(13)[1:]
    
    # Substituindo texto mês com a primeira letra não maiuscula
    #https://www.hashtagtreinamentos.com/pandas-where-ciencia-de-dados
    
    lista_unique_mes = dados_agua_df['MÊS'].unique()
   
    for i in range(len(meses)):
        dados_agua_df['MÊS'] = np.where(dados_agua_df['MÊS'] == meses[i].lower(), meses[i], dados_agua_df['MÊS'])
    lista_unique_mes = dados_agua_df['MÊS'].unique()
    
   
    # criando coluna df (MES_N) e associando com a coluna MES
   
    for i in range(len(meses)):
        if i == 0:
            dados_agua_df['MES_N'] = np.where(dados_agua_df['MÊS'] == meses[i], meses_n[i], 0)
        else:
            dados_agua_df['MES_N'] = np.where(dados_agua_df['MÊS'] == meses[i], meses_n[i], dados_agua_df['MES_N'])
    
    lista_unique_mes_N = dados_agua_df['MES_N'].unique()
   
    
    return dados_agua_df

#sub-def 14: -------------------------------------
## - corrige texto da coluna Mês e associa a coluna mês-N o número do mês

def inserir_coluna_datetime(dados_agua_df):

    #https://stackoverflow.com/questions/58072683/combine-year-month-and-day-in-python-to-create-a-date
    #inserir dia 20 a todos os registros
    dados_agua_df['DIA'] = 20
    df = dados_agua_df[['ANO','MES_N','DIA']]
    df.columns = ["year", "month", "day"]
    dados_agua_df['Dtime'] = pd.to_datetime(df)
    print('\n','Coluna Dtime no formato datetime com dia 20 atribuído inserida em dados_agua_df')
    return dados_agua_df


#sub-def 15: -------------------------------------
## - remover coluna Volume Consumido, pois não representa o consumo, apenas a diferença entre as leituras dos hidrômetros, 
## - e estas retornam a zero, o que gera valores negativos:
def remover_colunas(dados_agua_df):
    dados_agua_df = dados_agua_df.drop('VOLUME_CONSUMIDO', axis=1)
    dados_agua_df = dados_agua_df.drop('VERIFICACAO', axis=1)
    dados_agua_df = dados_agua_df.drop('DIFERENCA', axis=1)
    dados_agua_df = dados_agua_df.drop('DIA', axis=1)
    
    return dados_agua_df
 

#sub-def 16: -------------------------------------
## - exportar o arquivo para um csv unico:

def exportar_pd_unico_to_csv(dados_agua_df, pasta_projeto):
    pasta_produtos = os.path.join(pasta_projeto, 'Dados', 'Produtos')
    caminho_dados_agua_csv = os.path.join(pasta_produtos, 'dados_agua_df.csv')
    dados_agua_df.to_csv(caminho_dados_agua_csv)
    print('\n',f'dados_agua_df exportado em csv para a pasta: {pasta_produtos}')

#### Parte 1 - Gerar e exportar CSVs em separado do excel para uma pasta específica;
##### Rodar apenas para acessar e corrigir histórico de faturas no excel

In [7]:
# dados de entrada: nome do arquivo em excel para acesso às planilhas mensais
nome_arquivo_xls = 'M00 - Dados mensais_R5.xlsx'
gerar_csvs_a_partir_excel_func(nome_arquivo_xls)

Pasta projeto:  I:\Meu Drive\UFSC\PPGEA 2024\Python_for_env\ENS410064\Projeto

 Pasta dados origem : I:\Meu Drive\UFSC\PPGEA 2024\Python_for_env\ENS410064\Projeto\Dados\Origem

Pasta dados csv: I:\Meu Drive\UFSC\PPGEA 2024\Python_for_env\ENS410064\Projeto\Dados\Origem\CSVs

G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
G:\Meu Drive\pyenvcga\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)

 CSVs exportados com sucesso para a pasta I:\Meu Drive\UFSC\PPGEA 2024\Python_for_env\ENS410064\Projeto\Dados\Origem\CSVs.

 Foram exportados 143 arquivos com extensão csv.

 A pasta CSV possui ao todo 143 arquivos csv.

#### Parte 2 - Gerar df único a partir de dados em csv separados, e exportar csv único

In [11]:
chave = '2024_09_df' #### colunas de todos os dfs serão baseadas na df chave selecionada
dict_dfs = gerar_e_corrigir_dicionario_a_partir_csvs_func()
dados_agua_df = juntar_dfs_remover_NAN_e_exportar_func(chave, dict_dfs)

#visualizar os atributos do dataframe concatenado:
dados_agua_df.info()
#visualizar parte do dataframe concatenado:
display(dados_agua_df.iloc[80:90,:])
#visualizar estatísticas
dados_agua_df.describe()

Pasta projeto:  I:\Meu Drive\UFSC\PPGEA 2024\Python_for_env\ENS410064\Projeto

 Pasta dados origem : I:\Meu Drive\UFSC\PPGEA 2024\Python_for_env\ENS410064\Projeto\Dados\Origem
Pasta dados csv: I:\Meu Drive\UFSC\PPGEA 2024\Python_for_env\ENS410064\Projeto\Dados\Origem\CSVs
dict_keys(['2013_01_df', '2013_02_df', '2013_03_df', '2013_04_df', '2013_05_df', '2013_06_df', '2013_07_df', '2013_08_df', '2013_09_df', '2013_10_df', '2013_11_df', '2013_12_df', '2014_01_df', '2014_02_df', '2014_03_df', '2014_04_df', '2014_05_df', '2014_06_df', '2014_07_df', '2014_08_df', '2014_09_df', '2014_10_df', '2014_11_df', '2014_12_df', '2015_01_df', '2015_02_df', '2015_03_df', '2015_04_df', '2015_05_df', '2015_06_df', '2015_07_df', '2015_08_df', '2015_09_df', '2015_10_df', '2015_11_df', '2015_12_df', '2016_01_df', '2016_02_df', '2016_03_df', '2016_04_df', '2016_05_df', '2016_06_df', '2016_07_df', '2016_08_df', '2016_09_df', '2016_10_df', '2016_11_df', '2016_12_df', '2017_01_df', '2017_02_df', '2017_03_df', '2017_04_df', '2017_05_df', '2017_06_df', '2017_07_df', '2017_08_df', '2017_09_df', '2017_10_df', '2017_11_df', '2017_12_df', '2018_01_df', '2018_02_df', '2018_03_df', '2018_04_df', '2018_05_df', '2018_06_df', '2018_07_df', '2018_08_df', '2018_09_df', '2018_10_df', '2018_11_df', '2018_12_df', '2019_01_df', '2019_02_df', '2019_03_df', '2019_04_df', '2019_05_df', '2019_06_df', '2019_07_df', '2019_08_df', '2019_09_df', '2019_10_df', '2019_11_df', '2019_12_df', '2020_01_df', '2020_02_df', '2020_03_df', '2020_04_df', '2020_05_df', '2020_06_df', '2020_07_df', '2020_08_df', '2020_09_df', '2020_10_df', '2020_11_df', '2020_12_df', '2021_01_df', '2021_02_df', '2021_03_df', '2021_04_df', '2021_05_df', '2021_06_df', '2021_07_df', '2021_08_df', '2021_09_df', '2021_10_df', '2021_11_df', '2021_12_df', '2022_01_df', '2022_02_df', '2022_03_df', '2022_04_df', '2022_05_df', '2022_06_df', '2022_07_df', '2022_08_df', '2022_09_df', '2022_10_df', '2022_11_df', '2022_12_df', '2023_01_df', '2023_02_df', '2023_03_df', '2023_04_df', '2023_05_df', '2023_06_df', '2023_07_df', '2023_08_df', '2023_09_df', '2023_10_df', '2023_11_df', '2023_12_df', '2024_01_df', '2024_02_df', '2024_03_df', '2024_04_df', '2024_05_df', '2024_06_df', '2024_07_df', '2024_08_df', '2024_09_df', 'Auxiliar_referencia_df', 'Referencia_csv_df'])

 Verificação do número de colunas importadas em cada df:

0 2013_01_df 30 True
1 2013_02_df 30 True
2 2013_03_df 30 True
3 2013_04_df 30 True
4 2013_05_df 30 True
5 2013_06_df 30 True
6 2013_07_df 30 True
7 2013_08_df 30 True
8 2013_09_df 30 True
9 2013_10_df 30 True
10 2013_11_df 30 True
11 2013_12_df 30 True
12 2014_01_df 30 True
13 2014_02_df 30 True
14 2014_03_df 30 True
15 2014_04_df 30 True
16 2014_05_df 30 True
17 2014_06_df 30 True
18 2014_07_df 30 True
19 2014_08_df 30 True
20 2014_09_df 30 True
21 2014_10_df 30 True
22 2014_11_df 30 True
23 2014_12_df 30 True
24 2015_01_df 30 True
25 2015_02_df 30 True
26 2015_03_df 30 True
27 2015_04_df 30 True
28 2015_05_df 30 True
29 2015_06_df 30 True
30 2015_07_df 30 True
31 2015_08_df 30 True
32 2015_09_df 30 True
33 2015_10_df 30 True
34 2015_11_df 30 True
35 2015_12_df 30 True
36 2016_01_df 30 True
37 2016_02_df 30 True
38 2016_03_df 30 True
39 2016_04_df 30 True
40 2016_05_df 30 True
41 2016_06_df 30 True
42 2016_07_df 30 True
43 2016_08_df 30 True
44 2016_09_df 30 True
45 2016_10_df 30 True
46 2016_11_df 30 True
47 2016_12_df 30 True
48 2017_01_df 30 True
49 2017_02_df 30 True
50 2017_03_df 30 True
51 2017_04_df 30 True
52 2017_05_df 30 True
53 2017_06_df 30 True
54 2017_07_df 30 True
55 2017_08_df 30 True
56 2017_09_df 30 True
57 2017_10_df 30 True
58 2017_11_df 30 True
59 2017_12_df 30 True
60 2018_01_df 30 True
61 2018_02_df 30 True
62 2018_03_df 30 True
63 2018_04_df 30 True
64 2018_05_df 30 True
65 2018_06_df 30 True
66 2018_07_df 30 True
67 2018_08_df 30 True
68 2018_09_df 30 True
69 2018_10_df 30 True
70 2018_11_df 30 True
71 2018_12_df 30 True
72 2019_01_df 30 True
73 2019_02_df 30 True
74 2019_03_df 30 True
75 2019_04_df 30 True
76 2019_05_df 30 True
77 2019_06_df 30 True
78 2019_07_df 30 True
79 2019_08_df 30 True
80 2019_09_df 30 True
81 2019_10_df 30 True
82 2019_11_df 30 True
83 2019_12_df 30 True
84 2020_01_df 30 True
85 2020_02_df 30 True
86 2020_03_df 30 True
87 2020_04_df 30 True
88 2020_05_df 30 True
89 2020_06_df 30 True
90 2020_07_df 30 True
91 2020_08_df 30 True
92 2020_09_df 30 True
93 2020_10_df 30 True
94 2020_11_df 30 True
95 2020_12_df 30 True
96 2021_01_df 30 True
97 2021_02_df 30 True
98 2021_03_df 30 True
99 2021_04_df 30 True
100 2021_05_df 30 True
101 2021_06_df 30 True
102 2021_07_df 30 True
103 2021_08_df 30 True
104 2021_09_df 30 True
105 2021_10_df 30 True
106 2021_11_df 30 True
107 2021_12_df 30 True
108 2022_01_df 30 True
109 2022_02_df 30 True
110 2022_03_df 30 True
111 2022_04_df 30 True
112 2022_05_df 30 True
113 2022_06_df 30 True
114 2022_07_df 30 True
115 2022_08_df 30 True
116 2022_09_df 30 True
117 2022_10_df 30 True
118 2022_11_df 30 True
119 2022_12_df 30 True
120 2023_01_df 30 True
121 2023_02_df 30 True
122 2023_03_df 30 True
123 2023_04_df 30 True
124 2023_05_df 30 True
125 2023_06_df 30 True
126 2023_07_df 30 True
127 2023_08_df 30 True
128 2023_09_df 30 True
129 2023_10_df 30 True
130 2023_11_df 30 True
131 2023_12_df 30 True
132 2024_01_df 30 True
133 2024_02_df 30 True
134 2024_03_df 30 True
135 2024_04_df 30 True
136 2024_05_df 30 True
137 2024_06_df 30 True
138 2024_07_df 30 True
139 2024_08_df 30 True
140 2024_09_df 30 True

 Todos os 140 dfs importados possuem o mesmo número de colunas, ['CODIGO', 'CATEGORIA', 'ANO', 'MÊS', 'MATRICULA', 'CAMPUS', 'N_HIDROMETRO', 'COD_HIDROMETRO', 'CONCESSIONARIA', 'CIDADE', 'LOCAL', 'ECON_PUB', 'ECON_RES', 'ECON_COM', 'ECON_IND', 'ECON_TOTAL', 'LEIT_ANT', 'LEIT_ATUAL', 'VOLUME_CONSUMIDO', 'VOLUME_FATURADO', 'OCORRENCIA', 'ANORMALIDADE', 'VALOR_AGUA', 'VALOR_ESGOTO', 'DESCONTOS', 'OUTROS', 'MULTAS_JUROS', 'VALOR_TOTAL', 'VERIFICACAO', 'DIFERENCA']
Pasta projeto:  I:\Meu Drive\UFSC\PPGEA 2024\Python_for_env\ENS410064\Projeto

 dados_agua_df concatenado em um único arquivo dados_agua_df

 Total de linhas em dados_agua_df: 11210. Total de NANs em dados_agua_df: 26

 Coluna Dtime no formato datetime com dia 20 atribuído inserida em dados_agua_df

 dados_agua_df exportado em csv para a pasta: I:\Meu Drive\UFSC\PPGEA 2024\Python_for_env\ENS410064\Projeto\Dados\Produtos
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11184 entries, 0 to 11183
Data columns (total 29 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CODIGO           11184 non-null  object
 1   CATEGORIA        11184 non-null  object
 2   ANO              11184 non-null  object
 3   MÊS              11184 non-null  object
 4   MATRICULA        11148 non-null  object
 5   CAMPUS           9938 non-null   object
 6   N_HIDROMETRO     10082 non-null  object
 7   COD_HIDROMETRO   11184 non-null  object
 8   CONCESSIONARIA   11180 non-null  object
 9   CIDADE           11180 non-null  object
 10  LOCAL            11179 non-null  object
 11  ECON_PUB         10774 non-null  float64
 12  ECON_RES         5798 non-null   object
 13  ECON_COM         6513 non-null   float64
 14  ECON_IND         5864 non-null   float64
 15  ECON_TOTAL       11184 non-null  object
 16  LEIT_ANT         11059 non-null  object
 17  LEIT_ATUAL       11153 non-null  object
 18  VOLUME_FATURADO  11168 non-null  object
 19  OCORRENCIA       10281 non-null  object
 20  ANORMALIDADE     5719 non-null   object
 21  VALOR_AGUA       11163 non-null  float64
 22  VALOR_ESGOTO     9524 non-null   float64
 23  DESCONTOS        11019 non-null  float64
 24  OUTROS           6279 non-null   float64
 25  MULTAS_JUROS     7342 non-null   float64
 26  VALOR_TOTAL      11163 non-null  float64
 27  MES_N            11184 non-null  int32
 28  Dtime            11184 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(9), int32(1), object(18)
memory usage: 2.4+ MB

,CODIGO,CATEGORIA,ANO,MÊS,MATRICULA,CAMPUS,N_HIDROMETRO,COD_HIDROMETRO,CONCESSIONARIA,CIDADE,...,OCORRENCIA,ANORMALIDADE,VALOR_AGUA,VALOR_ESGOTO,DESCONTOS,OUTROS,MULTAS_JUROS,VALOR_TOTAL,MES_N,Dtime
80,H017 2013 Fevereiro,14,2013,Fevereiro,2296950,NaN,NaN,H017,CASAN,Florianópolis,...,NaN,NaN,6750.75,6750.75,-1275.89,NaN,NaN,12225.61,2,2013-02-20
81,H018 2013 Fevereiro,15,2013,Fevereiro,2296640,2013-02-20,A10C017754,H018,CASAN,Florianópolis,...,Lido,NaN,61.92,61.92,-11.70,NaN,NaN,112.14,2,2013-02-20
82,H019 2013 Fevereiro,16,2013,Fevereiro,9097821,2013-02-20,793193,H019,CASAN,Florianópolis,...,Lido,NaN,1142.78,1142.78,-216.00,NaN,NaN,2069.56,2,2013-02-20
83,H020 2013 Fevereiro,17,2013,Fevereiro,2296829,2013-02-20,C09B271060,H020,CASAN,Florianópolis,...,Lido,NaN,2710.27,2710.27,-512.25,NaN,NaN,4908.29,2,2013-02-20
84,H021 2013 Fevereiro,18,2013,Fevereiro,2296632,2013-02-20,B10C001813,H021,CASAN,Florianópolis,...,Médio,NaN,82.68,82.68,-15.62,NaN,NaN,149.74,2,2013-02-20
85,H023 2013 Fevereiro,19,2013,Fevereiro,2296934,2013-02-20,A93S053431,H023,CASAN,Florianópolis,...,Lido,NaN,2258.69,2258.69,-426.88,NaN,NaN,4090.50,2,2013-02-20
86,H024 2013 Fevereiro,20,2013,Fevereiro,2296926,2013-02-20,A96C161864,H024,CASAN,Florianópolis,...,Mínimo,NaN,82.68,82.68,-15.62,NaN,NaN,149.74,2,2013-02-20
87,H025 2013 Fevereiro,21,2013,Fevereiro,2296900,2013-02-20,D83S122687,H025,CASAN,Florianópolis,...,Lido,NaN,1537.04,1537.04,-290.50,NaN,NaN,2783.58,2,2013-02-20
88,H026 2013 Fevereiro,22,2013,Fevereiro,9912770,2013-02-20,A11C032293,H026,CASAN,Florianópolis,...,Lido,NaN,432.42,432.42,-81.73,NaN,NaN,783.11,2,2013-02-20
89,H027 2013 Fevereiro,23,2013,Fevereiro,2296888,2013-02-20,654300,H027,CASAN,Florianópolis,...,Informado,NaN,2815.87,2815.87,-532.20,NaN,NaN,5099.54,2,2013-02-20

,ECON_PUB,ECON_COM,ECON_IND,VALOR_AGUA,VALOR_ESGOTO,DESCONTOS,OUTROS,MULTAS_JUROS,VALOR_TOTAL,MES_N,Dtime
count,10774.000000,6513.000000,5864.000000,11163.000000,9524.000000,11019.000000,6279.000000,7.342000e+03,1.116300e+04,11184.000000,11184
mean,1.650640,0.443881,0.050989,3663.171287,3334.817260,-618.516020,50.762921,2.167080e+02,6.068372e+03,6.402092,2019-01-27 20:45:03.862660864
min,0.000000,0.000000,0.000000,0.000000,0.000000,-52346.220000,-7011.660000,-3.311376e+04,0.000000e+00,1.000000,2013-01-20 00:00:00
25%,1.000000,0.000000,0.000000,108.135000,42.510000,-468.825000,0.000000,0.000000e+00,1.577600e+02,3.000000,2016-03-20 00:00:00
50%,1.000000,0.000000,0.000000,683.400000,390.710000,-94.770000,0.000000,0.000000e+00,9.725700e+02,6.000000,2019-02-20 00:00:00
75%,1.000000,1.000000,0.000000,2820.795000,2308.960000,-12.500000,0.000000,0.000000e+00,4.407975e+03,9.000000,2021-12-20 00:00:00
max,51.000000,9.000000,1.000000,239568.120000,239568.120000,349.450000,18124.110000,1.222006e+06,1.415330e+06,12.000000,2024-09-20 00:00:00
std,5.687579,1.134920,0.219994,12160.283353,12636.822704,2229.827829,959.218069,1.427795e+04,2.563320e+04,3.423580,NaN